add the towards web3 native dapps zh
rooch-network/rooch-network.github.io pull request #128
Opened 2023-04-18 15:42 UTC by geometryolife

2023-04-19 03:41 UTC, Mine77 requested changes

2023-04-19 03:41 UTC, Mine77 commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +title: 迈向 Web3 原生 DApp
直接改成迈向 Web3 原生应用吧

2023-04-19 03:41 UTC, Mine77 commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +description: Web3 应用程序应该是去中心化的。然而，今天的 Web3 DApps 通常基于中心化架构。在本文中，我们讨论了我们对 Web3 Native 应用程序的愿景
Web3 Native 都统一翻译成 Web3 原生吧，或者是全文都叫 Web3 Native，用一个统一的用法

2023-04-19 03:41 UTC, Mine77 commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +在本文中，你会发现我们对 Web3 的看法。
这句话感觉略微有点生硬

2023-04-19 03:41 UTC, Mine77 commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +Web3 Native DApp 是指充分利用区块链技术提供的去中心化优势的 App。
感觉 DApp 和 App 的用法还是要统一一下：
中文文章里面统一用“应用”和“去中心化应用”吧

2023-04-19 03:41 UTC, Mine77 commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +  alt="Hello"
alt 要改一下 -> “Web3 原生应用”

2023-04-19 03:41 UTC, Mine77 commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +Hybrid Web3 App 通常采用与 Web2 App 相同的架构，用户从前端向后端服务器发送请求，由服务器进行计算和存储。它唯一的区别是，在后端服务器中，有一个私钥“代表”用户在去中心化的区块链上操作代币。
它唯一的区别是
->
它与 Web2 应用的唯一区别是

2023-04-19 03:41 UTC, Mine77 commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +Hybrid Web3 App 通常采用与 Web2 App 相同的架构，用户从前端向后端服务器发送请求，由服务器进行计算和存储。它唯一的区别是，在后端服务器中，有一个私钥“代表”用户在去中心化的区块链上操作代币。
有一个私钥
->
由一个私钥

2023-04-19 03:41 UTC, Mine77 commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +相比之下，A Web3 Native DApp 没有集中控制用户资产的私钥。DApp 的后端完全在智能合约运行时实现，它是公开、透明、无需许可的，正是智能合约定义的逻辑控制着从用户资产到 DApp 功能的一切。
正是智能合约定义的逻辑
->
由智能合约定义的逻辑

2023-04-19 03:41 UTC, Mine77 commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +## 分解 6 个问题
Web3 六问
或者其他什么
这个标题需要一个更顺耳的说法

2023-04-19 03:41 UTC, Mine77 commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +数据的价值来自数据属性的交易和对交易中特定方的数据可见性。而在 Web3 时代，代币代表数据归属和可见性，它们的价值将在更加自由和无摩擦的市场中被发现。
这句意思是说 数据的价值是在对数据归属权和数据的隐私设置这两者的交易过程中才体现的，如果只是放在那里也没什么价值

web3 里面我们可以用代币来代表这两个属性，通过交易代币来体现数据的价值，并且因为代币自身的属性，它的交易更顺滑，摩擦更小，所以它的价值发现过程会更有效

2023-04-19 03:51 UTC, geometryolife commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +description: Web3 应用程序应该是去中心化的。然而，今天的 Web3 DApps 通常基于中心化架构。在本文中，我们讨论了我们对 Web3 Native 应用程序的愿景
统一“Web3 原生”

2023-04-19 03:59 UTC, geometryolife commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +Web3 Native DApp 是指充分利用区块链技术提供的去中心化优势的 App。
中文标题修改成“迈向 Web3 原生去中心化应用”？ @Mine77

2023-04-19 04:13 UTC, Mine77 commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +Web3 Native DApp 是指充分利用区块链技术提供的去中心化优势的 App。
emmm
迈向 Web3 原生应用
吧？
但是迈向总感觉也不太对
或者就叫“Web3 原生应用”

2023-04-19 08:48 UTC, geometryolife commented
![image](https://user-images.githubusercontent.com/54882546/233020862-1233cbd2-5219-4752-bc3a-19bf83ab6c09.png)

在前言处罗列一个中英文术语对照，这样看起来会好些 @Mine77

2023-04-19 08:55 UTC, Mine77 commented
> ![image](https://user-images.githubusercontent.com/54882546/233020862-1233cbd2-5219-4752-bc3a-19bf83ab6c09.png)
> 
> 在前言处罗列一个中英文术语对照，这样看起来会好些 @Mine77

我感觉有点多余吧，视觉上不太好看，传播的时候也不好编辑传播，还是融合到文章里面吧，名词第一次出现的地方解释一下

2023-04-19 08:57 UTC, geometryolife commented
> 

好的

2023-04-19 09:03 UTC, geometryolife commented
![image](https://user-images.githubusercontent.com/54882546/233025320-1771581b-6fa4-4502-b616-4d598eff36b8.png)

这个形式如何？

2023-04-19 09:18 UTC, geometryolife commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +## 分解 6 个问题
Web3 六问不错👍

2023-04-19 09:42 UTC, geometryolife commented on pages/blog/towards-web3-native-dapps.zh-CN.mdx
> +在本文中，你会发现我们对 Web3 的看法。
已经有十多个出色的Web3基础设施正在不断突破区块链技术的界限，并试图将我们的行业推向更接近Web3梦想的目标。

在本文中，您将了解我们对Web3的愿景。

2023-04-20 02:24 UTC, Mine77 commented
> > ![image](https://user-images.githubusercontent.com/54882546/233025320-1771581b-6fa4-4502-b616-4d598eff36b8.png)
> > 这个形式如何？
> 
> 或者把“全称”-> “即” @Mine77

“即”好一点我觉得

2023-05-06 11:27 UTC, closed without merging